"""Shared limits for flow agent tool dispatch."""

TOOL_RESULT_PREVIEW_CHARS = 500
LLM_TOOL_RESULT_MAX_CHARS = 4000
TOOL_CONTEXT_NODES_MAX_BYTES = 65536
ALL_ITEMS_PROMPT_MAX_BYTES = 65536
FLOW_SUBFLOW_MAX_DEPTH = 4
FLOW_SUBFLOW_TIMEOUT_SECONDS = 120
FLOW_AGENT_STREAM_ROUND_SECONDS = 120
