apiVersion: v1
kind: ConfigMap
metadata:
  name: doc-router-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "doc-router.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.config.environment | quote }}
  NEXTAUTH_URL: {{ .Values.config.nextauthUrl | quote }}
  NEXT_PUBLIC_FASTAPI_FRONTEND_URL: {{ .Values.config.nextPublicFastapiUrl | quote }}
  FASTAPI_ROOT_PATH: {{ .Values.config.fastapiRootPath | quote }}
  FASTAPI_BACKEND_URL: {{ printf "http://backend.%s.svc.cluster.local:8000" .Release.Namespace | quote }}
  N_WORKERS: {{ .Values.config.nWorkers | quote }}
  AWS_S3_BUCKET_NAME: {{ .Values.config.appBucketName | quote }}
  AWS_REGION: {{ .Values.config.region | quote }}
